module.exports = {
    arrowParens: 'always',
    bracketSpacing: true,
    cursorOffset: -1,
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    pluginSearchDirs: [],
    plugins: [],
    printWidth: 91,
    proseWrap: 'preserve',
    quoteProps: 'as-needed',
    rangeEnd: Infinity,
    rangeStart: 0,
    requirePragma: false,
    semi: true,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'es5',
    useTabs: false,
    vueIndentScriptAndStyle: false,
};
